# -*- coding: utf-8 -*-
"""Projeto Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BsUsvI0titLV6Xj2ajrqmAMvA6V_Ic_D
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("https://raw.githubusercontent.com/Okamy28/TopicoBigData/main/Tabela_RJ_Covid_Completa.csv", sep = ";")
df.columns=['data', 'municipio', 'confirmados', 'confirmados100', 'obitos', 'mortalidade', 'obitos100']
print(df)

#  - Regressão Linear dos Casos de Covid -
coef_angular, intercepto = np.polyfit(df['obitos'], df['confirmados'], 1)
y_pred = coef_angular * df['obitos'] + intercepto

plt.scatter(df['obitos'], df['confirmados'], label='Dados Originais' )
plt.plot(df['obitos'], y_pred, color = 'red', linewidth = 2, label = "Linha de Regressão" )
plt.xlabel("Obitos por Covid")
plt.ylabel("Casos Confirmados de Covid")
plt.legend()
plt.title("Regressão Linear - Casos de Covid")
plt.grid(True)
plt.show()



# Analise estatisticas da coluna obitos por covid
Omedia = df['obitos'].mean()
Omoda = df['obitos'].mode()
Omediana = df['obitos'].median()
Odesvio = df['obitos'].std()

# Analise estatisticas da coluna Casos confirmados por Covid
Cmedia = df['confirmados'].mean()
Cmoda = df['confirmados'].mode()
Cmediana = df['confirmados'].median()
Cdesvio = df['confirmados'].std()

print("\n")
print("Analise Descritiva dos Óbitos")
print(f'Média: {Omedia}')
print(f'Mediana: {Omediana}')
print(f'Desvio Padrão: {Odesvio}')
print(f'moda: {Omoda}')
print("\n")
print("Analise Descritiva dos Casos Confirmados")
print(f'Média: {Cmedia}')
print(f'Mediana: {Cmediana}')
print(f'Desvio Padrão: {Cdesvio}')
print(f'moda: {Cmoda}')